const candidates = [
  {name:'Vefa',age:21,height:'1m 93',origin:'Turks',job:'Boekhouder & eigenaar van een pitta-zaak',bio:'Ondernemer met een flinke dosis energie. Vefa is getrouwd en staat open voor een tweede huwelijk; bespreek verwachtingen en praktische zaken zorgvuldig.',tags:[['🥙 Pitta Baroon','sage'],['🏎️ BMW Enthusiast',''],['📏 1m93','']],status:'Getrouwd · zoekt een tweede vrouw',statusTone:'coral',image:'assets/candidate-1.webp',alt:'Vefa bij zijn pitta-zaak'},
  {name:'Hussam',age:22,height:'1m 86',origin:'Syrisch',job:'Boekhouder & privéchauffeur',bio:'Sportief, gespierd en houdt van autorijden. Hussam is open over zijn voorkeur voor blondines; bespreek of jullie verwachtingen bij elkaar passen.',tags:[['🏋️‍♂️ Gespierd','sage'],['🚗 Renault Driver',''],['📚 Boekhouder','']],status:'Voorkeur: blondines',statusTone:'',image:'assets/candidate-2.webp',alt:'Hussam aan een terrastafel'},
  {name:'Pascal',age:23,height:'1m 78',origin:'Angolees',job:'Architect · interim-medewerker & privéchauffeur',bio:'Basketbalfan met brede interesses. Pascal heeft momenteel een vriendin en zoekt financiële steun voor haar; wees helder over grenzen, intenties en verwachtingen.',tags:[['📐 Architect','sage'],['🏀 Basketballer',''],['🍷 Houdt van witte wijn','coral']],status:'Heeft momenteel een vriendin',statusTone:'coral',image:'assets/candidate-3.webp',alt:'Pascal in een witte blouse'},
  {name:'Sukru',age:26,height:'1m 82',origin:'Turks',job:'Basketbaltrainer & eigenaar van een pitta-zaak',bio:'Basketbaltrainer en ondernemer. Sukru is momenteel werkloos en rijdt een Volkswagen.',tags:[['🏀 Basket Coach','sage'],['🥙 Pitta Master',''],['🚗 VW Club','']],status:'Werkloos',statusTone:'',image:'assets/candidate-4.webp',alt:'Sukru bij avondlicht'}
];
const grid=document.querySelector('#profile-grid');
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
grid.innerHTML=candidates.map((p,i)=>`<article class="profile-card" data-index="${i}"><div class="profile-photo"><img src="${p.image}" alt="${esc(p.alt)}" loading="lazy"><span class="profile-index">0${i+1} / 04</span></div><div class="profile-body"><div class="profile-topline"><div><h3 class="profile-name">${p.name}</h3><div class="profile-age">${p.age} jaar <span>·</span> ${p.height}</div></div><span class="profile-heart" aria-hidden="true">♡</span></div><p class="profile-bio">${p.bio}</p><div class="profile-meta"><span>✳</span>${p.origin} · ${p.job}</div><div class="tags">${p.tags.map(([t,k])=>`<span class="tag ${k}">${t}</span>`).join('')}</div><div class="tag ${p.statusTone}" style="display:inline-flex;margin-top:8px">${p.status}</div><button class="button button-dark apply-button" data-candidate="${i}">Interesse in ${p.name} <span>↗</span></button></div></article>`).join('');
grid.addEventListener('pointermove',e=>{const card=e.target.closest('.profile-card');if(!card||matchMedia('(hover: none)').matches)return;const r=card.getBoundingClientRect(),x=(e.clientX-r.left)/r.width-.5;card.style.setProperty('--tilt',`${x*3}deg`)});
grid.addEventListener('pointerleave',e=>{const card=e.target.closest('.profile-card');if(card)card.style.setProperty('--tilt','0deg')},true);
const backdrop=document.querySelector('#modal-backdrop'),modalContent=document.querySelector('#modal-content'),closeButton=document.querySelector('.modal-close');let activeCandidate=0,previousFocus=null;
function openModal(index){activeCandidate=index;previousFocus=document.activeElement;const p=candidates[index];modalContent.innerHTML=`<div class="modal-kicker">EEN RUSTIGE EERSTE STAP</div><h2 class="modal-title" id="modal-title">Vertel iets<br><em>over jezelf.</em></h2><p class="modal-intro">Laat weten waarom je interesse hebt in ${p.name}. De beheerder beoordeelt elke aanvraag handmatig. Er is geen directe chat.</p><div class="selected-person"><span>Jouw interesse gaat uit naar</span><b>${p.name} · ${p.age}</b></div><form id="application-form"><div class="form-grid"><div class="field"><label for="app-name">Je naam *</label><input id="app-name" name="name" autocomplete="name" required maxlength="80" placeholder="Voor- en achternaam"></div><div class="field"><label for="app-age">Je leeftijd *</label><input id="app-age" name="age" type="number" min="18" max="100" required placeholder="Bijv. 27"></div><div class="field full"><label for="app-contact">E-mail of WhatsApp *</label><input id="app-contact" name="contact" required maxlength="120" placeholder="Hoe mogen we je bereiken?"></div><div class="field full"><label for="app-motivation">Korte voorstelling of motivatie *</label><textarea id="app-motivation" name="motivation" required maxlength="700" placeholder="Vertel wat je graag wilt delen …"></textarea></div><div class="field full"><label for="app-wali">Contact van je wali of begeleider</label><input id="app-wali" name="wali" maxlength="120" placeholder="Naam + e-mail of telefoon (aanbevolen)"><p class="form-hint">Betrokkenheid van een wali of neutrale begeleider wordt aangemoedigd.</p></div></div><label class="consent"><input type="checkbox" name="consent" required><span>Ik begrijp dat dit een demo is: mijn gegevens worden niet opgeslagen of verstuurd. Ik ga akkoord met een respectvolle, begeleide kennismaking. *</span></label><div class="form-note">✳ Elke aanvraag wordt eerst handmatig beoordeeld. Er is geen privéchat of automatisch contact met de kandidaat.</div><button class="button button-dark submit-button" type="submit">Bekijk demo-bevestiging <span>↗</span></button></form>`;backdrop.hidden=false;document.body.style.overflow='hidden';document.querySelector('#app-name').focus()}
function closeModal(){backdrop.hidden=true;document.body.style.overflow='';if(previousFocus)previousFocus.focus()}
grid.addEventListener('click',e=>{const b=e.target.closest('.apply-button');if(b)openModal(Number(b.dataset.candidate))});closeButton.addEventListener('click',closeModal);backdrop.addEventListener('click',e=>{if(e.target===backdrop)closeModal()});
document.addEventListener('keydown',e=>{if(e.key==='Escape'&&!backdrop.hidden)closeModal();if(e.key==='Tab'&&!backdrop.hidden){const items=[...backdrop.querySelectorAll('button,input,textarea,[href]')].filter(x=>!x.disabled);if(!items.length)return;const first=items[0],last=items.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus()}}});
backdrop.addEventListener('submit',e=>{if(e.target.id!=='application-form')return;e.preventDefault();if(!e.target.reportValidity())return;const p=candidates[activeCandidate];modalContent.innerHTML=`<div class="success-view"><div class="success-mark">✓</div><div class="modal-kicker">BEDANKT VOOR JE OPENHEID</div><h2 class="modal-title" id="modal-title">Je eerste stap<br><em>is gezet.</em></h2><p>Je demo-aanmelding voor ${p.name} is compleet. Er is niets verzonden of bewaard. In een echte omgeving zou de beheerder je aanvraag eerst zorgvuldig beoordelen.</p><button class="button button-dark" id="success-close">Terug naar de profielen <span>↗</span></button></div>`;document.querySelector('#success-close').addEventListener('click',closeModal);confetti()});
function confetti(){const canvas=document.querySelector('#confetti'),ctx=canvas.getContext('2d');canvas.width=innerWidth*devicePixelRatio;canvas.height=innerHeight*devicePixelRatio;ctx.scale(devicePixelRatio,devicePixelRatio);const colors=['#d6a64b','#d98570','#557966','#e3c778','#f5efe0'];const bits=Array.from({length:90},()=>({x:innerWidth*.5+(Math.random()-.5)*240,y:innerHeight*.38+(Math.random()-.5)*100,vx:(Math.random()-.5)*7,vy:-Math.random()*8-2,size:Math.random()*7+3,rot:Math.random()*6,vr:(Math.random()-.5)*.25,color:colors[Math.floor(Math.random()*colors.length)],life:100+Math.random()*40}));let frame=0;function draw(){ctx.clearRect(0,0,innerWidth,innerHeight);for(const b of bits){b.x+=b.vx;b.y+=b.vy;b.vy+=.16;b.rot+=b.vr;b.life--;ctx.save();ctx.translate(b.x,b.y);ctx.rotate(b.rot);ctx.globalAlpha=Math.max(0,Math.min(1,b.life/35));ctx.fillStyle=b.color;ctx.fillRect(-b.size/2,-b.size/2,b.size,b.size*.65);ctx.restore()}if(++frame<130)requestAnimationFrame(draw);else ctx.clearRect(0,0,canvas.width,canvas.height)}draw()}
const phrases=['Op jouw tempo.','Met iemand naast je.','Met een open hart.'];let phrase=0;const typeEl=document.querySelector('#typewriter');setInterval(()=>{phrase=(phrase+1)%phrases.length;typeEl.style.opacity=0;setTimeout(()=>{typeEl.textContent=phrases[phrase];typeEl.style.opacity=1},220)},3200);
const menu=document.querySelector('.menu-toggle'),nav=document.querySelector('.site-header nav');menu.addEventListener('click',()=>{const open=nav.classList.toggle('open');menu.setAttribute('aria-expanded',String(open))});nav.addEventListener('click',e=>{if(e.target.closest('a')){nav.classList.remove('open');menu.setAttribute('aria-expanded','false')}});

